version: '2.1'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf:ro
      - ./main:/var/www/html:ro
  php:
    build:
      context: ./docker/php
      args:
        USER: #leave it empty to use your current user
        UID: ${UID:-1000} # https://docs.docker.com/compose/compose-file/#variable-substitution
    volumes:
      - ./main:/var/www/html
      - ./data:/srv/data
