version: '2.1'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html:ro
  php:
    build:
      context: ./docker/php
      args:
        USER: #leave it empty to use your current user
        UID: ${UID:-1000} # https://docs.docker.com/compose/compose-file/#variable-substitution
    volumes:
      - ./src:/var/www/html
      - ./data/.todo:/home/www-data/.todo:ro
      - ./data/todo-txt:/todo-txt
